# -*- coding: utf-8 -*-
"""Maze.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nFHgjbb78WX0yC6XhN1bFMge5Z4aaVf0
"""

board = HexBoard()
centre = (8,8)
board.init_circular(8)
board.generate_maze(centre, 0.5)
display("Random circular maze with dimensions r = 8, start = (8,8) with no color and branching factor 0.5 (Uncolored)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

board = HexBoard()
centre = (7,7)
board.init_rectangular(15,15)
board.generate_maze(centre, 0.5)
display("Random rectangular maze with dimensions h = 15, w = 15, start = (7,7) and branching factor 0.5 (Uncolored)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

board = HexBoard()
centre = (8,8)
board.init_circular(8)
board.generate_maze(centre, 0.5)
board.color_board(centre, "path")
display("Random circular maze with dimensions r = 8, start = (8,8) with no color and branching factor 0.5 (Colored with path distance)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

board = HexBoard()
centre = (8,8)
board.init_circular(8)
board.generate_maze(centre, 0.5)
board.color_board(centre, "cell")
display("Random circular maze with dimensions r = 8 and start = (8,8) and branching factor 0.5 (Colored with cell distance)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

board = HexBoard()
centre = (8,8)
board.init_circular(8)
board.generate_maze(centre, 0)
display("Random circular maze with dimensions r = 8, start = (8,8) and branching factor 0 (Uncolored)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

board = HexBoard()
centre = (7,7)
board.init_rectangular(15,15)
board.generate_maze(centre, 1)
display("Random rectangular maze with dimensions h = 15, w = 15, start = (7,7) and branching factor 1 (Uncolored)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

board = HexBoard()
centre = (8,8)
board.init_circular(8)
board.generate_maze(centre, 0.15)
board.color_board(centre, "path")
display("Random circular maze with dimensions r = 8, start = (8,8) and branching factor 0.15 (Colored based on path distance)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

board = HexBoard()
centre = (8,8)
board.init_rectangular(10,25)
board.generate_maze(centre, 0.5)
board.color_board(centre, "path")
display("Random circular maze with dimensions h = 10, w = 25, start = (8,8) and branching factor 0.5 (Colored based on path distance)", draw_maze(board, 20))
display("Solution", draw_solution(board, 20))

